exercises = [
{ label = "Supine Straight Leg Straight Right", reps = 10 },
{ label = "Supine Straight Leg Out Right", reps = 10 },
{ label = "Prone Leg Lift Straight Right", reps = 10 },
{ label = "Prone Left Lift Out Right", reps = 10 }
]
