exercises = [
  { label = "Left Step-Up", reps = 25 },
  { label = "Right Step-Up", reps = 25 },
  { label = "Left Split Squat", reps = 10 },
  { label = "Right Split Squat", reps = 10 },
  { label = "Wall Slides", reps = 10 },
]

