exercises = [
  { label = "Right Hamstring Stretch", reps = 10 },
  { label = "Left Hamstring Stretch", reps = 10 },
  { label = "Right IT Band Stretch", reps = 10 },
  { label = "Left IT Band Stretch", reps = 10 },
  { label = "Right Knee to Left Shoulder Stretch", reps = 10 },
  { label = "Left Knee to Right Shoulder Stretch", reps = 10 },
  { label = "Right Banded Clam Shell x 15", reps = 1 },
  { label = "Left Banded Clam Shell x 15", reps = 1 },
  { label = "Right Quad Stretch", reps = 10 },
  { label = "Left Quad Stretch", reps = 10 },
  { label = "Right Step-Up x 20", reps = 3 },
  { label = "Left Step-Up x 20", reps = 3 },
  { label = "Right 3-Way Leg Swing x 10", reps = 3 },
  { label = "Left 3-Way Leg Swing x 10", reps = 3 },
  { label = "Right Split Squat x 15", reps = 1 },
  { label = "Left Split Squat x 15", reps = 1 },
]
