exercises = [
  { label = "ITB Right", reps = [
    1,
    2,
    3,
    4,
    5,
  ] },
  { label = "ITB Left", reps = [
    1,
    2,
    3,
    4,
    5,
  ] },
  { label = "Piriformis Right", reps = [
    1,
    2,
    3,
    4,
    5,
  ] },
  { label = "Piriformis Left", reps = [
    1,
    2,
    3,
    4,
    5
  ] },
  { label = "Butterfly", reps = [
    1,
    2,
    3,
    4,
    5,
  ] },
  { label = "Marching w/Resistance", reps = [
    1,
    2,
    3,
    4,
    5,
    6, 7, 8,
  ] },
  { label = "Squats", reps = [
    1,
    2,
    3,
    4,
    5, 6,7,8,
  ] },
  { label = "Clamshell Right", reps = [
    1,
    2,
    3,
    4,
    5, 6,7,8,
  ] },
  { label = "Clamshell Left", reps = [
    1,
    2,
    3,
    4,
    5, 6,7,8,
  ] },
]
