exercises = [
  { label = "Right Hamstring Stretch", reps = 15 },
  { label = "Left Hamstring Stretch", reps = 15 },
  { label = "Right IT Band Stretch", reps = 15 },
  { label = "Left IT Band Stretch", reps = 15 },
  { label = "Right Quad Stretch", reps = 15 },
  { label = "Left Quad Stretch", reps = 15 },
  { label = "Right Step-Up x 20", reps = 2 },
  { label = "Left Step-Up x 20", reps = 2 },
  { label = "Right Split Squat x 15", reps = 1 },
  { label = "Left Split Squat x 15", reps = 1 },
  { label = "Wall Slides", reps = 10 },
]
