exercises = [
  { label = "ITB Right", reps = 5 },
  { label = "ITB Left", reps = 5 },
  { label = "Piriformis Right", reps = 5 },
  { label = "Piriformis Left", reps = 5 },
  { label = "Butterfly", reps = 5 },
  { label = "Marching w/Resistance", reps = 8 },
  { label = "Squats", reps = 8 },
  { label = "Clamshell Right", reps = 8 },
  { label = "Clamshell Left", reps = 8 },
]
