exercises = [
  { label = "Right Hamstring Stretch", reps = 10 },
  { label = "Left Hamstring Stretch", reps = 10 },
  { label = "Right IT Band Stretch", reps = 10 },
  { label = "Left IT Band Stretch", reps = 10 },
  { label = "Right Calf Stretch", reps = 10 }, 
  { label = "Left Calf Stretch", reps = 10 },
  { label = "Right Quad Stretch", reps = 10 },
  { label = "Left Quad Stretch", reps = 10 },
  { label = "Right Step-Up x 20", reps = 2 },
  { label = "Left Step-Up x 20", reps = 2 },
  { label = "Right 3-Way Leg Swing x 20", reps = 1 },
  { label = "Left 3-Way Leg Swing x 20", reps = 1 },
  { label = "Right Split Squat x 15", reps = 1 },
  { label = "Left Split Squat x 15", reps = 1 },
  { label = "Wall Slides", reps = 10 },
]
